// Forwarding a member's request with sensitive secrets put in. This file is
// the whole mechanism and knows no service: it replaces one piece of text
// with another, wherever it appears, in a request to a host the owner
// allowed. See docs/managed-keys.md.

/** A sensitive secret used in one request, opened for it. */
export interface Substitution {
  /** What the member's program was given in place of the value. */
  placeholder: string;
  value: Uint8Array;
  /** The hosts the owner allowed, from inside the sealed content. */
  hosts: string[];
}

/** A request to forward, as the member's envrune sent it. */
export interface ForwardRequest {
  method: string;
  target: string;
  headers: [string, string][];
  body: Uint8Array | null;
}

export class ForwardRefused extends Error {
  status: number;
  constructor(status: number, message: string) {
    super(message);
    this.status = status;
  }
}

/** Placeholders are generated by envrune; anything else is not replaced. */
export const placeholderPattern = /^envrune_sealed_[0-9a-f]{32}$/;

/** Bodies larger than this are forwarded as they are, without looking inside. */
export const maxTextBody = 4 * 1024 * 1024;

// Headers that belong to one connection, or that this server sets itself.
const dropped = new Set([
  "host",
  "connection",
  "keep-alive",
  "proxy-authenticate",
  "proxy-authorization",
  "proxy-connection",
  "te",
  "trailer",
  "transfer-encoding",
  "upgrade",
  "content-length",
  "accept-encoding",
]);

/**
 * Checks where a request is going. Only HTTPS on the standard port, to a
 * host that every secret used in it allows: a request cannot carry a secret
 * to a host its owner did not name.
 */
export function checkTarget(target: string, substitutions: Substitution[]): URL {
  let url: URL;
  try {
    url = new URL(target);
  } catch {
    throw new ForwardRefused(400, "the address to forward to is not valid");
  }
  if (url.protocol !== "https:" || url.port !== "" || url.username !== "" || url.password !== "") {
    throw new ForwardRefused(400, "sensitive secrets are sent only over https, on the standard port");
  }
  const host = url.hostname.toLowerCase();
  for (const s of substitutions) {
    if (!s.hosts.includes(host)) {
      throw new ForwardRefused(403, `a sensitive secret in this request may not be sent to ${host}`);
    }
  }
  return url;
}

function isText(contentType: string): boolean {
  return /^(text\/|application\/(json|x-www-form-urlencoded|xml|graphql)|application\/[a-z0-9.+-]*\+(json|xml))/i.test(contentType.trim());
}

function replaceAll(text: string, from: string, to: string): string {
  return from === "" ? text : text.split(from).join(to);
}

/** Replaces every placeholder in text; `into` says which way. */
function swap(text: string, substitutions: Substitution[], into: "request" | "response"): string {
  for (const s of substitutions) {
    const value = Buffer.from(s.value).toString("utf8");
    text = into === "request" ? replaceAll(text, s.placeholder, value) : replaceAll(text, value, s.placeholder);
  }
  return text;
}

/**
 * A header value with placeholders replaced. Basic credentials are base64,
 * so they are decoded, replaced, and encoded again.
 */
function swapHeader(name: string, value: string, substitutions: Substitution[], into: "request" | "response"): string {
  const basic = name === "authorization" && /^Basic\s+(\S+)$/i.exec(value);
  if (basic) {
    const decoded = Buffer.from(basic[1], "base64").toString("utf8");
    const swapped = swap(decoded, substitutions, into);
    return swapped === decoded ? value : `Basic ${Buffer.from(swapped, "utf8").toString("base64")}`;
  }
  return swap(value, substitutions, into);
}

/** The request to send upstream: the member's, with the values put in. */
export function buildUpstream(request: ForwardRequest, substitutions: Substitution[]): { url: string; init: RequestInit } {
  for (const s of substitutions) {
    if (!placeholderPattern.test(s.placeholder)) {
      throw new ForwardRefused(400, "a placeholder in this request was not made by envrune");
    }
  }
  const url = checkTarget(request.target, substitutions);
  if (substitutions.some((s) => url.hostname.includes(s.placeholder))) {
    throw new ForwardRefused(400, "a placeholder cannot be part of the host");
  }
  // After the host is settled, the path and the query may carry the value.
  const upstream = new URL(swap(url.toString(), substitutions, "request"));
  if (upstream.host !== url.host || upstream.protocol !== "https:") {
    throw new ForwardRefused(400, "the value would change where the request goes");
  }
  const headers = new Headers();
  let contentType = "";
  for (const [rawName, value] of request.headers) {
    const name = rawName.toLowerCase();
    if (dropped.has(name) || name.startsWith("x-envrune-")) {
      continue;
    }
    if (name === "content-type") {
      contentType = value;
    }
    headers.append(name, swapHeader(name, value, substitutions, "request"));
  }
  // Responses are read as sent, so the value can be taken out of them.
  headers.set("accept-encoding", "identity");
  let body: Uint8Array | null = request.body;
  if (body && body.length > 0 && body.length <= maxTextBody && isText(contentType)) {
    body = Buffer.from(swap(Buffer.from(body).toString("utf8"), substitutions, "request"), "utf8");
  }
  const method = request.method.toUpperCase();
  return {
    url: upstream.toString(),
    init: {
      method,
      headers,
      body: method === "GET" || method === "HEAD" ? undefined : (body as BodyInit | null),
      // A redirect could lead elsewhere with the value attached.
      redirect: "manual",
    },
  };
}

/**
 * The response for the member's program: the upstream's, with any echo of a
 * value turned back into its placeholder, in headers and in text bodies.
 */
export async function buildResponse(upstream: Response, substitutions: Substitution[]): Promise<Response> {
  const headers = new Headers();
  upstream.headers.forEach((value, name) => {
    if (!dropped.has(name) && name !== "content-encoding") {
      headers.append(name, swapHeader(name, value, substitutions, "response"));
    }
  });
  headers.set("x-envrune-forward", "upstream");
  const init = { status: upstream.status, statusText: upstream.statusText, headers };
  if (upstream.body === null || upstream.status === 204 || upstream.status === 304) {
    return new Response(null, init);
  }
  const length = Number(upstream.headers.get("content-length") ?? "-1");
  if (!isText(upstream.headers.get("content-type") ?? "") || length > maxTextBody) {
    return new Response(upstream.body, init);
  }
  const raw = Buffer.from(await upstream.arrayBuffer());
  if (raw.length > maxTextBody) {
    return new Response(raw, init);
  }
  return new Response(Buffer.from(swap(raw.toString("utf8"), substitutions, "response"), "utf8"), init);
}
