package cli

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"github.com/YagoLagrottiBracco/envrune/internal/project"
)

// generatedMarker starts every file `envrune types` writes, so it can tell
// its own files from hand-written ones.
const generatedMarker = "Generated by `envrune types` from envrune.yml"

// types writes typed settings for the variables of envrune.yml. It reads no
// values, so it needs no unlock.
func (w Workspace) types(argv []string) int {
	const usage = "types [ts|python] [--output <path>|-] [--force]"
	a, err := parseArgs(argv, []string{"output"}, []string{"force"}, false)
	if err != nil || len(a.positional) > 1 {
		return w.usageError(usage)
	}
	language := "ts"
	if len(a.positional) == 1 {
		language = a.positional[0]
	}
	projectPath, err := w.findProject()
	if err != nil {
		return w.fail(err, "No Envrune project configuration was found.")
	}
	config, err := project.Load(projectPath)
	if err != nil {
		return w.fail(err, "The project configuration is invalid.")
	}
	var content []byte
	var defaultName string
	switch language {
	case "ts", "typescript":
		content, defaultName = typescriptTypes(settingsOf(config)), "env.d.ts"
	case "python", "py":
		content, defaultName = pythonSettings(settingsOf(config)), "settings.py"
	default:
		return w.usageError(usage)
	}
	output := a.options["output"]
	if output == "-" {
		_, _ = w.Stdout.Write(content)
		return 0
	}
	if output == "" {
		output = filepath.Join(filepath.Dir(projectPath), defaultName)
	}
	if existing, err := os.ReadFile(output); err == nil && !bytes.Contains(existing, []byte(generatedMarker)) && !a.flags["force"] {
		w.status().Error(fmt.Sprintf("%s exists and was not generated by EnvRune. Choose another --output, or replace it with --force.", output))
		return 1
	}
	if err := os.WriteFile(output, content, 0644); err != nil {
		return w.fail(err, "Could not write "+output+".")
	}
	w.status().Success(fmt.Sprintf("Wrote %s with %d variables.", output, len(settingsOf(config))))
	return 0
}

// setting is one variable as the generated code declares it.
type setting struct {
	project.Variable
	documented bool
}

// settingsOf lists the documented variables in order, then the variables
// some environment links without documenting them, as optional strings.
func settingsOf(config project.Config) []setting {
	var out []setting
	seen := map[string]bool{}
	for _, v := range config.Variables {
		out = append(out, setting{v, true})
		seen[v.Name] = true
	}
	var extra []string
	for _, mappings := range config.Environments {
		for name := range mappings {
			if !seen[name] {
				seen[name] = true
				extra = append(extra, name)
			}
		}
	}
	sort.Strings(extra)
	for _, name := range extra {
		out = append(out, setting{project.Variable{Name: name}, false})
	}
	return out
}

func (s setting) comment() string {
	var parts []string
	if s.Description != "" {
		parts = append(parts, strings.TrimSuffix(s.Description, ".")+".")
	}
	if s.Type == "url" || s.Type == "int" || s.Type == "bool" {
		parts = append(parts, "Type: "+s.Type+".")
	}
	if s.Format != "" {
		parts = append(parts, "Format: "+s.Format)
	}
	if !s.documented {
		parts = append(parts, "Not documented under variables: in envrune.yml.")
	}
	return strings.Join(parts, " ")
}

// typescriptTypes declares the variables on process.env. Values in the
// environment are always strings, whatever their type in envrune.yml.
func typescriptTypes(settings []setting) []byte {
	var b bytes.Buffer
	fmt.Fprintf(&b, "// %s. Do not edit; run `envrune types` again instead.\n\n", generatedMarker)
	b.WriteString("declare namespace NodeJS {\n  interface ProcessEnv {\n")
	for _, s := range settings {
		if c := s.comment(); c != "" {
			fmt.Fprintf(&b, "    /** %s */\n", strings.ReplaceAll(c, "*/", "* /"))
		}
		optional := ""
		if !s.Required {
			optional = "?"
		}
		fmt.Fprintf(&b, "    readonly %s%s: string;\n", s.Name, optional)
	}
	b.WriteString("  }\n}\n\nexport {};\n")
	return b.Bytes()
}

// pythonSettings declares a pydantic-settings class that reads and checks
// the variables.
func pythonSettings(settings []setting) []byte {
	var b bytes.Buffer
	fmt.Fprintf(&b, "# %s. Do not edit; run `envrune types python` again instead.\n", generatedMarker)
	b.WriteString("from pydantic import AnyUrl, Field\nfrom pydantic_settings import BaseSettings\n\n\n")
	b.WriteString("class Settings(BaseSettings):\n")
	if len(settings) == 0 {
		b.WriteString("    pass\n")
	}
	for _, s := range settings {
		kind := map[string]string{"url": "AnyUrl", "int": "int", "bool": "bool"}[s.Type]
		if kind == "" {
			kind = "str"
		}
		var args []string
		// pydantic applies pattern only to strings.
		pattern := s.Format != "" && kind == "str"
		if !s.Required {
			kind += " | None"
			args = append(args, "default=None")
		}
		if s.Description != "" {
			args = append(args, "description="+strconv.Quote(s.Description))
		}
		if pattern {
			args = append(args, "pattern="+strconv.Quote(s.Format))
		}
		if !s.documented {
			b.WriteString("    # Not documented under variables: in envrune.yml.\n")
		}
		if len(args) == 0 {
			fmt.Fprintf(&b, "    %s: %s\n", s.Name, kind)
		} else {
			fmt.Fprintf(&b, "    %s: %s = Field(%s)\n", s.Name, kind, strings.Join(args, ", "))
		}
	}
	return b.Bytes()
}
